name: Create and publish a Docker image to AWS ECR, Deploy to Cloudtype

on:
  push:
    branches:
      - master

env:
  REGISTRY: ${{ secrets.AWS_ECR_REGISTRY }}
  AWS_REGION: ap-northeast-2
  IMAGE_NAME: fast-api-example
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Config AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        run: |
          docker build -t $REGISTRY/$IMAGE_NAME:$GITHUB_SHA .
          docker push $REGISTRY/$IMAGE_NAME:$GITHUB_SHA
